### PR TITLE
Add SynoCommunity V3 link

### PR DESCRIPTION
**Pull request by Safihre**

### CODE REVIEW

**Comment by bakerboy448** [comment]
@Safihre 

Per Taloth on my PR ".html is generated. update the marko file and use yarn/gulp to generate it."

**Comment by Safihre** [comment]
No one even cared to respond to this pull request.. I can change it, but I don't understand why @Taloth wouldn't comment that here. It takes time to setup the yarn gulp thing, why would I invest the time if no one will look at the PR?

**Comment by bakerboy448** [comment]
Honestly, he probably just missed it. Or they may not want to link to the v3 package until it is ironed out.  Just conjecture. 

The website is relatively static these days (as one would expect)

**Comment by Taloth** [comment]
Yeah, I totally missed the PR. sry Safihre

**Comment by Safihre** [comment]
Awesome, thanks 👍

**Pull request closed without merging**
