### PR TITLE
Images Updated to V3

### PR DESCRIPTION
**Pull request by TRaSH-**
Updated v2 images to v3
Let me know if you need other images
By request @bakerboy448

### CODE REVIEW

**Comment by bakerboy448** [comment]
Need to adjust the sizes of the images and possibly/probably the layout itself
image
image
image
image


Also need updated images for:
- calendar
- Manual Search
- automated failed download handling

image

**Comment by TRaSH-** [comment]
> Also need updated images for:
> 
> * calendar
> * Manual Search
> * automated failed download handling

Added these updated images
added 2 variant of the calendar.

I left them original size, let me know if you want them resized and to which format.

**Comment by TRaSH-** [comment]
> Need to adjust the sizes of the images and possibly/probably the layout itself

Are these created automatically ? or actual images ?

**Comment by bakerboy448** [comment]
the screenshots are from building the site locally based on this PR

**Comment by TRaSH-** [comment]
> the screenshots are from building the site locally based on this PR

So what needs to be done, or anything i can do ?
resize images ?

**Comment by bakerboy448** [comment]
based on the recent commits

- [ ] can we get an updated manual search with the scene mapping icons?
- [ ] Calendar needs to be reijjgered
- otherwise imo looks good
image
image
image
image
image
image
image

**Comment by TRaSH-** [comment]
> based on the recent commits
> 
> * [x]  can we get an updated manual search with the scene mapping icons?
> * [ ]  Calendar needs to be reijjgered
> * otherwise imo looks good

https://github.com/Sonarr/sonarr.github.io/pull/17/commits/563fb574b776c985f98905c7c38088105cc2790f

**Comment by bakerboy448** [comment]
@Taloth  I think all that was needed here was some re-writing of how the images are organized? Is that something you or @markus101 can take care of? I don't think that's something that Trash and I are knowledgeable enough to do.

**Pull request closed without merging**
