### PR TITLE
Add Sonarr v3 download section

### PR DESCRIPTION
**Pull request by Taloth**
Work in progress.

I also added browser-sync and `gulp serve` to access it locally.

I really wish we could just throw webcomponents or something in there and use a prerenderer, but that was more work than I'm comfortable, so just bootstrap html for now.
Advantage of doing webcomponents/react would be that we could isolate each installation into a separate file.

Minimalistic Windows:

image

Advanced usage is collapsed:
image

Debian/Ubuntu is almost complete imo:

image

MacOS:

image

Docker & Others are TBD:
OThers contains "Please contact us if you wish to port Sonarr v3 Beta for any other platform that the ones already listed.
Sonarr v2 is supported by various third-parties on other platforms and we prefer to coordinate the port of v3."

### CODE REVIEW

**Review by markus101 — APPROVED** [review]
Any reason to not link to the docker image as we did for the alpha?

React/something would definitely be nice, but I was in the same boat, didn't want to commit to it and run into issues.

I like this, looks great, just the docker question, but otherwise looks good to land.

**Comment by Taloth** [comment]
sonarr-preview docker is likely still tied to phantom instead of phantom-develop, right? So wanted to get that sorted out before listing it on the site. And I think we need to include additional guidance with regards to permissions and volumes.

Btw. iirc you use the container for your production environment. Do you let the built in updater do the updates, or do you update the container periodically?

**Comment by Taloth** [comment]
Docker instructions:

image

**Comment by markus101** [comment]
Yeah, it's using `phantom` and that container is a bit weird in the fact that we asked them to re-downlaod the image on boot instead of a package install because we didn't have such a v3 package at the time. We can ask them to fix that though.

I use the built-in updater, I know it's not the recommended way to do it, but it makes the most sense to me from ease of updating. The current container could shoot me in the foot on reboot due to the downgrade to `phantom` from `phantom-develop` though.

**Comment by Taloth** [comment]
So suggesting them to add a package_info that blocks the built-in updater would actually be an issue for some people.

**Comment by markus101** [comment]
In my eyes, definitely.

**Pull request merged**
